-define(DB_USER_NAME, "root").
-define(DB_PASSWORD, "*").
-define(DB_HOSTNAME, "localhost").
-define(DB_DEFAULT_DB, "mysql").
-define(DB_DEFAULT_TABLE, "db").
-define(DB_PORT, 3306).
-define(DB_CONN_NUM, 10).
